volumes:
  data:

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: "db"
      POSTGRES_USER: "AT_HW_7"
      POSTGRES_PASSWORD: "AT_HW_7"
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql